### PR TITLE
add typescript support

### PR DESCRIPTION
**Pull request by miguelcobain**
- extracted `register` function
- exported `register` function
- added `index.d.ts` typings file

Looks really cool. :)

addresses #3 

``` ts
import web, { controller, get, use } from 'express-decorators';

@controller('/hello')
export default class TestController {

  @get('/hello')
  list(request, response) {
    response.send('hello, world!');
  }

}
```

### CODE REVIEW

**Comment by miguelcobain** [comment]
I added the possibility to not provide a path, defaulting it to `/`.
This allows me to write `@controller()` and `@get()`.

**Comment by stewartml** [comment]
Thanks @miguelcobain, I'll try to look at this later today.

**Comment by miguelcobain** [comment]
Ok. All tests are passing.

**Comment by stewartml** [comment]
Apologies, I have no idea where the time goes...   My day job saps up all my time and energy at the moment.

Not all of this is related to the stated purpose of the PR, namely "add typescript support"; e.g., why did you refactor the register function and export it?

Knowing very little about typescript, I'm just kind of taking your word for it that it is correct (I'm sure it is ;)) - is there something we could add like a unit test or something which demonstrates that the ts file is correct?

If not I guess I can just accept it and see if anyone else submits a bug!

**Comment by miguelcobain** [comment]
@stewartml no problem at all. I can relate. :)

The problem was that the register function was basically being "injected" in the class at the runtime by the decorator.
If you're used to typed languages, this isn't really compatible with the paradigm.
Basically, typescript couldn't know that the class has a `register` method and we get an error when trying to call it.

So, I basically export the `register` method and I declare it in the typings file. It is a "functional" approach instead of an OOP one. Another option would be to add a superclass that has a register method and then all our controllers would need to inherit it, but I felt that to be more intrusive.

This was an experiment. I ended up not using this in production, but it worked just fine in my tests.
Also, the tests pass, so you can be certain it won't break existing functionality.

I'm not aware of any typescript test of that sort. I'm also fairly new at typescript. :)
In any case, I believe that this is a step forward for typescript users.

It's your call and your project. No problem. :)

**Comment by rundef** [comment]
:+1:

**Comment by stewartml** [comment]
@miguelcobain I finally got around to learning TypeScript...

I've rewritten this library in TypeScript now, so the definitions are there.  I took your suggestions onboard about separating out the `register` function as well.

**Pull request closed without merging**
